#theme: jekyll-theme-minimal
#title: Written by Bhagwan Shree Swaminarayan's own blissful hand on Vasant Panchmi of Vikram Samvat 1882 (C.E. 1826), this is a booklet of 212 Shlokas. Shreeji Maharaj sat in the Hari Mandap – His residence at Vadtal Mandir – and wrote it in Sanskrit. He instructed the pandit Sadguru Shree Nityanand Swami to translate it into Gujarati. It has since been translated numerous times into other languages.

It contains general guidance and specific instructions to a variety of categories of followers – the Acharyas & their wives, householder males and females, widows, saints and brahmacharies.

On February 20th, 1830 Maharaj went to visit the British Governor, Sir John Malcolm, in Rajkot. He was received with a guard of honor by the infantry and the cavalry. The Governor himself received Maharaj and offered Him a royal chair. Then he presented Him with a shawl. Maharaj presented the Governor with a Shikshapatri which has to this day been very carefully preserved in the Bodleian Library at the University of Oxford.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
