#theme: jekyll-theme-minimal
#title: The original Shikshapatri written by Bhagwan Shree Swaminarayan in Vadtal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
